//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoBufObject.proto
namespace Ragnarok.Test.Net
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoBufObject")]
  public partial class ProtoBufObject : global::ProtoBuf.IExtensible
  {
    public ProtoBufObject() {}
    
    private int _Index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Index
    {
      get { return _Index; }
      set { _Index = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private double _Value;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double Value
    {
      get { return _Value; }
      set { _Value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoBufList")]
  public partial class ProtoBufList : global::ProtoBuf.IExtensible
  {
    public ProtoBufList() {}
    
    private readonly global::System.Collections.Generic.List<Ragnarok.Test.Net.ProtoBufObject> _List = new global::System.Collections.Generic.List<Ragnarok.Test.Net.ProtoBufObject>();
    [global::ProtoBuf.ProtoMember(1, Name=@"List", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Ragnarok.Test.Net.ProtoBufObject> List
    {
      get { return _List; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}